# Use the latest 2.1 version of CircleCI pipeline processing engine, see https://circleci.com/docs/2.0/configuration-reference/
version: 2

# Orchestrate or schedule a set of jobs, see https://circleci.com/docs/2.0/workflows/
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - tag-sample:
          filters:
            tags:
              only: /^[0-9]{8}/

jobs:
  build:
    docker:
      - image: circleci/ruby:2.5.0-node-browsers
    steps:
      - checkout
      - run: env | sort
      - run:
          command: |
            sudo apt-get -y -qq update
            sudo apt-get install python-pip python-dev build-essential
            sudo pip install awscli
            aws --version
      - run: echo "hello world!!"

  tag-sample:
    docker:
      - image: circleci/ruby:2.5.0-node-browsers
    steps:
      - checkout
      - run: env | sort
      - run: echo "hello tag!!"
